### ISSUE TITLE
Mathematical operations

### ISSUE THREAD

**Issue by kahaaga** [kahaaga/UncertainData.jl#28]
We now support some statistical methods. However, it would be nice to do as Measurements.jl and support the elementary mathematical methods, so that common operations "just work" (e.g. addition, subtraction). Should be combined with #27.

## Implemented operations for uncertain values

- [x] Addition. Added in #30.
- [x] Subtraction. Added in #30.
- [x] Multiplication Added in #30.
- [x] Division. Added in #30.

## Implemented operations for uncertain datasets

- [x] Addition.
- [x] Subtraction.
- [x] Multiplication
- [x] Division.
